name: CI

on:
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0  

      - name: Set up Python
        uses: actions/setup-python@v4.2.0  
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python blog_project/manage.py migrate

      - name: Run tests
        run: |
          python blog_project/manage.py test
